Sinatra課題提出
sadanora/sinatra-practice pull request #1
Opened 2021-11-26 00:42 UTC by sadanora

2021-12-01 00:58 UTC, u1tnk requested changes
<img width="802" alt="image" src="https://user-images.githubusercontent.com/279240/144152230-08c5d17e-b97b-46f7-a8dc-30c46cad91bc.png">

単純に手順通り実行して新規作成するとこうなりました。
手順にディレクトリ作成があるべきとうのもありますが、処理の中に「ディレクトリが無かったら作る」という処理があれば手順も無くてよりスマートですね。

2021-12-01 00:58 UTC, u1tnk commented on README.md
> +# 注意点
3系で確認しようとしてたので親切ですね 👍 

rbenv使っていると思いますので、 `rbenv local 2.7.2`を実行して `.ruby-version` をコミットしておくとより良かったですね。

2021-12-01 00:58 UTC, u1tnk commented on app.rb
> +  @memo_title = h(memo['title'])
escape処理はcontrollerでやってしまうと、その後加工しづらくなったりしてしまうので、viewで表示するときにやると良いですね。

2021-12-01 00:58 UTC, u1tnk commented on app.rb
> +    hash = json_to_hash("./public/memos/#{file_name}")
hashという変数名は型名以外の情報が無くてよくないです。内容に即せば`memo`が良いでしょう。
(ちなみに型名は極力付けない方が良いです)

ただ、この場合一行しか使わないので
`@memos.push(json_to_hash....)` 
と変数作らない方が良いとは思います。

2021-12-01 14:07 UTC, sadanora commented
レビューいただきありがとうございます！
memosディレクトリが存在しない場合について、考慮が漏れていました:bow:
ディレクトリがない場合は作成するようにしました。

その他ご指摘いただいた点も修正いたしました。
再度ご確認のほどよろしくお願いいたします。

2021-12-02 03:32 UTC, u1tnk requested changes

2021-12-02 03:32 UTC, u1tnk commented on app.rb
> +  memo = json_to_hash("./public/memos/#{@memo_id}.json")
この `memo`を `@memo` としてerbに渡すぐらいが一般的だと思います。

2021-12-02 11:47 UTC, sadanora commented on app.rb
> +  memo = json_to_hash("./public/memos/#{@memo_id}.json")
再レビューありがとうございます。@memoとしてハッシュごとviewに渡すように変更しました。
@memo_idもいちいち変数に格納しなくてよいのかな、と思いparams[:memo_id]を直接参照するようにしています。

2021-12-02 12:44 UTC, u1tnk commented on app.rb
> +  memo = json_to_hash("./public/memos/#{@memo_id}.json")
paramsをviewsに使うのは微妙なところですが、微妙なので大丈夫です 🙆‍♀️
今後のRailsではやらないようにしましょう。

2021-12-02 12:44 UTC, u1tnk approved these changes

2021-12-02 14:22 UTC, sadanora commented on app.rb
> +  memo = json_to_hash("./public/memos/#{@memo_id}.json")
>paramsをviewsに使うのは微妙なところ

なるほど、その辺りの感覚もRailsのプラクティスを進める際に学んでいきたいと思います。
レビューありがとうございました！

2021-12-02 14:22 UTC, merged